### ISSUE TITLE
Getting an error when running the bot.

### ISSUE THREAD

**Issue by Jammo13** [Nabrok/gw2-discord-bot#17]
![image](https://cloud.githubusercontent.com/assets/27573948/25065887/cf988330-21d4-11e7-8451-85786959170f.png)

**Comment by gruntzy** [comment]
The bot requires [nodejs](https://nodejs.org/en/download/) to run, make sure you installed it, and then install the dependencies with the `npm install` command

Then, try to run the bot with `npm start`, or try to run it by calling nodejs directly (I'm not sure about the command on Windows, but it should be something like `node .\discord_bot.js`)

**Comment by Jammo13** [comment]
Thank you for the quick response, I just installed nodejs. Just wondering so I was able to get everything setup but I did get a few errors just wondering if there is something I missed.


ranks feature requires a guild ID and key.
motd requires Guild ID, Guild Key, and MOTD channel in config
bot ready
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! discord_bot@1.0.0 start: `node discord_bot.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the discord_bot@1.0.0 start script 'node discord_bot.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the discord_bot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node discord_bot.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs discord_bot
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls discord_bot
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Not For You\Desktop\gw2-discord-bot-master\npm-debug.log

**Comment by gruntzy** [comment]
The bot also uses **redis** to store data, which I forgot to mention before. 
You need to install redis on your computer, but It is not officialy supported on Windows platforms. 
There is a port for windows on github  (see https://github.com/MSOpenTech/redis), you probably need to have a look at it to make the bot work properly.

**Comment by Nabrok** [comment]
Going to close this as it's an issue with installing redis.
