### ISSUE TITLE
Missing null check on id field

### ISSUE THREAD

**Issue by siemandelc** [Nabrok/gw2-discord-bot#18]
Not sure what triggered it, but it took the bot offline

![capture](https://cloud.githubusercontent.com/assets/1727967/25233691/607005e4-25a5-11e7-9ffd-7a9a79beb2a1.PNG)

**Comment by Nabrok** [comment]
This is an odd one, not sure how it was getting to that part of the code without a valid user object, but it does seem to happen sometimes when !whois is called without a valid mention.

This commit should prevent the bot crashing if that does happen.
