### ISSUE TITLE
Bot unable to update MotD?

### ISSUE THREAD

**Issue by siemandelc** [Nabrok/gw2-discord-bot#20]
![capture](https://cloud.githubusercontent.com/assets/1727967/25388103/7b798342-2992-11e7-9288-0a544bb310dd.PNG)

This worked before this commit https://github.com/Nabrok/gw2-discord-bot/commit/3177953dbc27b27035138630f8e5f50e06fa180f

**Comment by Nabrok** [comment]
This error would have occurred if it didn't find a channel name that matches the config setting guild.motd_channel.  Note that this config setting should be the channel *name*, not the *id*.

I've updated the message when this happens so that it is a bit more informative.
