### ISSUE TITLE
Need to copy linked APIs from old server to new server

### ISSUE THREAD

**Issue by myurkoski** [Nabrok/gw2-discord-bot#35]
Nabrok,

We had a large server that had a couple hundred users with linked APIs. We had to migrate the server after a crash, but don't want everyone to have to relink if possible. Can you tell me how/where the linked APIs are stored so that I may retrieve them from the old HDD (which is fine) and put them into the new system? 

Thanks,
M Yurkoskis

**Comment by Nabrok** [comment]
It is saved in a redis database, here are some instructions for backing it up/moving to another server: https://stackoverflow.com/questions/6004915/how-do-i-move-a-redis-database-from-one-server-to-another
