### ISSUE TITLE
People that moved servers dont always have their role revoked

### ISSUE THREAD

**Issue by noskillahh** [Nabrok/gw2-discord-bot#37]
Hi Nabrok, 

sorry for bothering you again. It has come to our attention that the gw2 world based roles arent always properly revoked when people move servers. I have checked the registered api key and the gw2 acc in question is not residing on the configured world id. I understand that the roles are checked when the Discord status of the linked discord account changes. The account we are checking right now is permanently in the busy status. We have not manually removed any roles to see what the bot does. The user has moved servers over 7 days ago. The bot has been restarted as a test 5 days ago. The user still has the old server roles assigned.

**Comment by Nabrok** [comment]
You're right.  I'll try and get a fix for that up shortly.

**Comment by noskillahh** [comment]
You're the best!

On 29 Jul 2019, at 19:53, Nabrok <notifications@github.com<mailto:notifications@github.com>> wrote:


You're right. I'll try and get a fix for that up shortly.

**Comment by Nabrok** [comment]
I just pushed up some changes, it should update all member account data when the bot is restarted and then once a day after that.

You can adjust the frequency it updates with new config file option refresh_member_interval.

**Comment by noskillahh** [comment]
Hey Nabrok, thanks for the super quick solution! I updated my bot and seconds within it starting up several members had their roles revoked. The ones I checked have indeed moved servers. 

Is there any chance I can easily get this paired up with the world role function, so their new server also gets visible? This way its easy for everyone to see whats going on with the roles.

**Comment by Nabrok** [comment]
It should already be doing that.  Is it not?

**Comment by noskillahh** [comment]
It seems like it is doing a similar thing as the “link” feature did before the fix - people that never change status never get their tole updated. So now the link feature is fixed also for people using the busy status all the time, but their server role stays as if they never moved at all.

**Comment by Nabrok** [comment]
It seems to be working on my test server.  I manually removed my current server role and assigned another one and when I restarted the bot it switched me back.
