### ISSUE TITLE
sor discord bot

### ISSUE THREAD

**Issue by MouseHudmaeden** [Nabrok/gw2-discord-bot#38]
Seems the bot is not working with the !last session command. fab bot though Nabrok <3

**Comment by Nabrok** [comment]
Do you have discord setup to show when you are playing Guild Wars 2 or not?  That's how it knows when to snapshot your account and then make a comparison.

**Comment by MouseHudmaeden** [comment]
aye i do.....[salt] Mathew was having issues :)
love the bot Nabrok :)

     On Sunday, September 29, 2019, 6:18:29 PM PDT, Nabrok <notifications@github.com> wrote:  
 
 
Do you have discord setup to show when you are playing Guild Wars 2 or not? That's how it knows when to snapshot your account and then make a comparison.
